### ISSUE TITLE
在 conf.py 中配置 copyright 信息后，生成的 PDF 文件不能显示配置值

### ISSUE THREAD

**Issue by justdn** [ikiwihome/sphinx_evas_theme#2]
首先感谢模版分享，第一次使用，尝试修改 `titlepage.tex` 失败，所以没法提交 PR，可能是 bug，不是的话，期望能得到帮助🙏。

### Problem

生成的 PDF 文件中，首页左下版权提示总是显示：`©2024 EVAS Intelligence, all rights reserved`

### Reproducible Project

1. 配置 conf.py，取消 copyright 签名的注释，设置一个值
2. make clean && make pdf

#### Expected Results

应与 conf.py 中配置的 copyright 值一致

### Environment Info

- Python Version: 3.10
- Sphinx Version: 5.0.2
- RTD Theme Version: 1.4 / 1.5(main branch)

**Comment by ikiwihome** [comment]
©2024 EVAS Intelligence, all rights reserved  这是个单独的latex语句，在titlepage.tex里面删除如下语句，或者改成你希望的就可以：

\begin{minipage}[b]{20cm}
	\vspace{4em}\hspace{1cm}
	\large{©\the\year\hspace{0.3em} EVAS Intelligence, all rights reserved}\smallskip\newline
\end{minipage}
